name: deploy

on:
  push:
    branches: [ CICD ]

jobs:
  build:
    runs-on: ubuntu-latest

    env: 
      CI: false

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: './bootcampfire/package-lock.json'
      
      - name: Install modules
        run: npm install

      - name: Run test codes
        run: npm run test

      - name: Build project
        run: npm run build

      - name: Deploy test
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          password: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd bootcampfire/
            npx pm2 kill
            git pull
            npm i
            npx pm2 start App.tsx