name: deploy

on:
  push:
    branches: [ CICD ]

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "./bootcampfire"

    env: 
      CI: false

    strategy:
      matrix:
        node-version: [18.16.1]

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: './package-lock.json'
      
      - name: Install modules
        run: npm i -g pnpm

      # - name: Run test codes
      #   run: pnpm run test

      # - name: Build project
      #   run: pnpm i && pnpm start

      - name: Deploy EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          password: ${{ secrets.EC2_KEY }}
          # port: ${{ secrets.PORT }}
          script: |
            cd bootcampfire/
            git pull
            pnpm start